// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api/v1` | (string & {});
};

export type ErrorResponse = {
    error: {
        code: string;
        message: string;
        details?: {
            [key: string]: unknown;
        };
    };
};

export type PaginationMeta = {
    page: number;
    limit: number;
    total: number;
    totalPages: number;
};

export type TimeRange = {
    startTime: string;
    endTime: string;
};

export type AuthResponse = {
    accessToken: string;
    refreshToken: string;
    /**
     * Token expiration in seconds
     */
    expiresIn: number;
    user: User;
};

export type Building = {
    id: string;
    name: string;
    description?: string;
    location?: string;
    createdAt: string;
    updatedAt: string;
};

export type CreateBuildingRequest = {
    name: string;
    description?: string;
    location?: string;
};

export type UpdateBuildingRequest = {
    name?: string;
    description?: string;
    location?: string;
};

export type PaginatedBuildingList = {
    data: Array<Building>;
    meta: PaginationMeta;
};

export type Blocking = {
    id: string;
    entityType: 'building' | 'area' | 'place';
    entityId: string;
    blockingType: 'closedHours' | 'weekend' | 'holiday' | 'maintenance' | 'event' | 'disabled' | 'custom';
    name?: string | null;
    reason?: string | null;
    startTime: string;
    endTime: string;
    isRecurring: boolean;
    /**
     * iCal RRULE format
     */
    recurrenceRule?: string | null;
    /**
     * ISO 8601 duration
     */
    recurrenceDuration?: string | null;
    recurrenceEnd?: string | null;
    /**
     * Read-only, indicates source of blocking
     */
    source: 'own' | 'inheritedFromArea' | 'inheritedFromBuilding';
    createdAt: string;
    updatedAt: string;
};

export type CreateBlockingRequest = {
    blockingType: 'closedHours' | 'weekend' | 'holiday' | 'maintenance' | 'event' | 'disabled' | 'custom';
    name?: string;
    reason?: string;
    startTime: string;
    endTime: string;
    isRecurring?: boolean;
    /**
     * iCal RRULE format (required if isRecurring=true)
     */
    recurrenceRule?: string;
    /**
     * ISO 8601 duration (required if isRecurring=true)
     */
    recurrenceDuration?: string;
    recurrenceEnd?: string;
};

export type Area = {
    id: string;
    buildingId: string;
    name: string;
    description?: string;
    location?: string;
    roomPlan?: RoomPlan;
    createdAt: string;
    updatedAt: string;
};

export type CreateAreaRequest = {
    buildingId: string;
    name: string;
    description?: string;
    location?: string;
};

export type UpdateAreaRequest = {
    name?: string;
    description?: string;
    location?: string;
};

export type PaginatedAreaList = {
    data: Array<Area>;
    meta: PaginationMeta;
};

export type RoomPlan = {
    imageUrl: string;
    markers: Array<PlaceMarker>;
};

export type PlaceMarker = {
    id: string;
    placeId: string;
    /**
     * X position as percentage (0-100)
     */
    x: number;
    /**
     * Y position as percentage (0-100)
     */
    y: number;
    width: number;
    height: number;
    shape: 'rectangle' | 'circle';
};

export type CreatePlaceMarkerRequest = {
    placeId: string;
    x: number;
    y: number;
    width: number;
    height: number;
    shape: 'rectangle' | 'circle';
};

export type PlaceAvailability = {
    placeId: string;
    placeName: string;
    status: 'available' | 'partiallyAvailable' | 'fullyBooked' | 'blocked' | 'disabled';
    nextAvailableSlot?: string | null;
    blockedReason?: string | null;
    blockedSource?: 'place' | 'area' | 'building';
};

export type Place = {
    id: string;
    areaId: string;
    name: string;
    description?: string;
    location?: string;
    capacity: number;
    isBookable: boolean;
    bookingMethod: 'selfService' | 'manual';
    isDisabled: boolean;
    requiresCheckIn: boolean;
    equipment?: Array<Equipment>;
    constraints?: PlaceConstraints;
    timeSlotConfig?: TimeSlotConfig;
    createdAt: string;
    updatedAt: string;
};

export type CreatePlaceRequest = {
    areaId: string;
    name: string;
    description?: string;
    location?: string;
    capacity?: number;
    isBookable?: boolean;
    bookingMethod?: 'selfService' | 'manual';
    requiresCheckIn?: boolean;
};

export type UpdatePlaceRequest = {
    name?: string;
    description?: string;
    location?: string;
    capacity?: number;
    isBookable?: boolean;
    bookingMethod?: 'selfService' | 'manual';
    isDisabled?: boolean;
    requiresCheckIn?: boolean;
};

export type PaginatedPlaceList = {
    data: Array<Place>;
    meta: PaginationMeta;
};

export type PlaceConstraints = {
    /**
     * ISO 8601 duration
     */
    maxReservationDuration?: string | null;
    /**
     * ISO 8601 duration
     */
    minReservationDuration?: string | null;
    maxReservationsPerDay?: number | null;
    maxReservationsPerWeek?: number | null;
    maxReservationsPerMonth?: number | null;
    maxReservationsPerYear?: number | null;
    maxHoursPerDay?: number | null;
    maxHoursPerWeek?: number | null;
    maxHoursPerMonth?: number | null;
    maxHoursPerYear?: number | null;
    maxConcurrentReservations?: number | null;
    maxAdvanceBookingDays?: number | null;
    checkInTimeoutMinutes?: number | null;
    decayTimeoutMinutes?: number | null;
    whitelistEnabled?: boolean;
};

export type TimeSlotConfig = {
    /**
     * Booking grid interval (e.g., 15, 30, 60)
     */
    intervalMinutes: number;
    /**
     * Earliest valid booking start time (e.g., "08:00")
     */
    earliestStartTime?: string | null;
    /**
     * Latest valid booking end time (e.g., "20:00")
     */
    latestEndTime?: string | null;
};

export type AvailabilitySlot = {
    startTime: string;
    endTime: string;
    status: 'available' | 'blocked' | 'reserved';
    blockingReason?: string | null;
    blockingSource?: 'place' | 'area' | 'building';
    reservationId?: string | null;
};

export type Reservation = {
    id: string;
    placeId: string;
    userId: string;
    startTime: string;
    endTime: string;
    status: 'pending' | 'confirmed' | 'checkedIn' | 'completed' | 'cancelled' | 'expired';
    checkInTime?: string | null;
    cancelReason?: string | null;
    isRecurring: boolean;
    recurringGroupId?: string | null;
    createdAt: string;
    updatedAt: string;
};

export type CreateReservationRequest = {
    placeId: string;
    startTime: string;
    endTime: string;
    recurrence?: {
        pattern?: 'daily' | 'weekly' | 'biweekly' | 'monthly';
        endDate?: string;
        /**
         * Days of week (0=Sunday, 6=Saturday) for weekly patterns
         */
        daysOfWeek?: Array<number>;
    };
};

export type UpdateReservationRequest = {
    startTime?: string;
    endTime?: string;
};

export type PaginatedReservationList = {
    data: Array<Reservation>;
    meta: PaginationMeta;
};

export type ShareResponse = {
    shareUrl: string;
    previewMetadata: {
        title: string;
        description: string;
        image?: string;
        siteName: string;
    };
};

export type User = {
    id: string;
    email: string;
    username: string;
    name: string;
    profilePicture?: string;
    oauthProvider: string;
    oauthId?: string;
    isActive: boolean;
    groups?: Array<Group>;
    createdAt: string;
    updatedAt: string;
};

export type UserReference = {
    id: string;
    email: string;
    name: string;
};

export type UpdateUserRequest = {
    groupIds?: Array<string>;
};

export type PaginatedUserList = {
    data: Array<User>;
    meta: PaginationMeta;
};

export type NotificationPreferences = {
    reservationConfirmed?: boolean;
    reservationCancelled?: boolean;
    reservationReminder?: boolean;
    reminderMinutesBefore?: number;
    checkInWarning?: boolean;
};

export type Group = {
    id: string;
    name: string;
    description?: string;
    /**
     * True for immutable "system" group
     */
    isSystem: boolean;
    /**
     * True for editable "default" group
     */
    isDefault: boolean;
    permissions?: Array<Permission>;
    createdAt: string;
    updatedAt: string;
};

export type GroupWithMembers = Group & {
    members?: Array<UserReference>;
};

export type CreateGroupRequest = {
    name: string;
    description?: string;
    permissions?: Array<string>;
};

export type UpdateGroupRequest = {
    name?: string;
    description?: string;
};

export type Permission = {
    name: string;
    description: string;
};

export type Equipment = {
    id: string;
    name: string;
    icon?: string;
    description?: string;
};

export type CreateEquipmentRequest = {
    name: string;
    icon?: string;
    description?: string;
};

export type UpdateEquipmentRequest = {
    name?: string;
    icon?: string;
    description?: string;
};

export type Statistics = {
    totalBuildings?: number;
    totalAreas?: number;
    totalPlaces?: number;
    totalReservations?: number;
    totalUsers?: number;
    currentActiveReservations?: number;
    currentCheckedIn?: number;
};

export type UsageStatistics = {
    period: string;
    startDate: string;
    endDate: string;
    reservationCount?: number;
    checkInCount?: number;
    uniqueUsers?: number;
    averageOccupancy?: number;
    peakOccupancy?: number;
};

export type CurrentOccupancy = {
    totalPlaces?: number;
    occupiedPlaces?: number;
    availablePlaces?: number;
    occupancyRate?: number;
    checkedInCount?: number;
};

export type QrTemplate = {
    id: string;
    name: string;
    /**
     * HTML template with placeholders
     */
    htmlTemplate: string;
    createdAt: string;
    updatedAt: string;
};

export type CreateQrTemplateRequest = {
    name: string;
    htmlTemplate: string;
};

export type UpdateQrTemplateRequest = {
    name?: string;
    htmlTemplate?: string;
};

export type ApiKey = {
    id: string;
    name: string;
    /**
     * First 8 characters for identification
     */
    keyPrefix: string;
    /**
     * Inherited from creating user
     */
    permissions: Array<string>;
    lastUsedAt?: string | null;
    expiresAt?: string | null;
    createdAt: string;
};

export type ApiKeyWithSecret = ApiKey & {
    /**
     * Full API key (only shown once at creation)
     */
    key: string;
};

export type CreateApiKeyRequest = {
    name: string;
    expiresAt?: string;
};

export type AuditLogEntry = {
    id: string;
    entityType: 'building' | 'area' | 'place' | 'reservation' | 'user' | 'group';
    entityId: string;
    action: 'create' | 'update' | 'delete';
    userId: string;
    /**
     * Before/after values for updates
     */
    changes?: {
        [key: string]: unknown;
    };
    timestamp: string;
};

export type PaginatedAuditLogList = {
    data: Array<AuditLogEntry>;
    meta: PaginationMeta;
};

/**
 * Page number (1-indexed)
 */
export type PageParam = number;

/**
 * Items per page
 */
export type LimitParam = number;

export type BuildingIdParam = string;

export type AreaIdParam = string;

export type PlaceIdParam = string;

export type ReservationIdParam = string;

export type UserIdParam = string;

export type GroupIdParam = string;

export type EquipmentIdParam = string;

export type TemplateIdParam = string;

export type InitiateOAuthLoginData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type HandleOAuthCallbackData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Authorization code from GitLab
         */
        code: string;
        /**
         * CSRF protection state
         */
        state: string;
    };
    url: '/auth/callback';
};

export type HandleOAuthCallbackErrors = {
    /**
     * Bad request - validation error
     */
    400: ErrorResponse;
    /**
     * Unauthorized - not authenticated
     */
    401: ErrorResponse;
};

export type HandleOAuthCallbackError = HandleOAuthCallbackErrors[keyof HandleOAuthCallbackErrors];

export type HandleOAuthCallbackResponses = {
    /**
     * Successful authentication
     */
    200: AuthResponse;
};

export type HandleOAuthCallbackResponse = HandleOAuthCallbackResponses[keyof HandleOAuthCallbackResponses];

export type RefreshTokenData = {
    body: {
        refreshToken: string;
    };
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type RefreshTokenErrors = {
    /**
     * Unauthorized - not authenticated
     */
    401: ErrorResponse;
};

export type RefreshTokenError = RefreshTokenErrors[keyof RefreshTokenErrors];

export type RefreshTokenResponses = {
    /**
     * New tokens generated
     */
    200: AuthResponse;
};

export type RefreshTokenResponse = RefreshTokenResponses[keyof RefreshTokenResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type LogoutResponses = {
    /**
     * Session invalidated
     */
    204: void;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type GetCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type GetCurrentUserErrors = {
    /**
     * Unauthorized - not authenticated
     */
    401: ErrorResponse;
};

export type GetCurrentUserError = GetCurrentUserErrors[keyof GetCurrentUserErrors];

export type GetCurrentUserResponses = {
    /**
     * Current user profile
     */
    200: User;
};

export type GetCurrentUserResponse = GetCurrentUserResponses[keyof GetCurrentUserResponses];

export type ListBuildingsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number (1-indexed)
         */
        page?: number;
        /**
         * Items per page
         */
        limit?: number;
        /**
         * Search by name
         */
        search?: string;
    };
    url: '/buildings';
};

export type ListBuildingsResponses = {
    /**
     * List of buildings
     */
    200: PaginatedBuildingList;
};

export type ListBuildingsResponse = ListBuildingsResponses[keyof ListBuildingsResponses];

export type CreateBuildingData = {
    body: CreateBuildingRequest;
    path?: never;
    query?: never;
    url: '/buildings';
};

export type CreateBuildingErrors = {
    /**
     * Bad request - validation error
     */
    400: ErrorResponse;
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
};

export type CreateBuildingError = CreateBuildingErrors[keyof CreateBuildingErrors];

export type CreateBuildingResponses = {
    /**
     * Building created
     */
    201: Building;
};

export type CreateBuildingResponse = CreateBuildingResponses[keyof CreateBuildingResponses];

export type DeleteBuildingData = {
    body?: never;
    path: {
        buildingId: string;
    };
    query?: never;
    url: '/buildings/{buildingId}';
};

export type DeleteBuildingErrors = {
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type DeleteBuildingError = DeleteBuildingErrors[keyof DeleteBuildingErrors];

export type DeleteBuildingResponses = {
    /**
     * Building deleted
     */
    204: void;
};

export type DeleteBuildingResponse = DeleteBuildingResponses[keyof DeleteBuildingResponses];

export type GetBuildingData = {
    body?: never;
    path: {
        buildingId: string;
    };
    query?: never;
    url: '/buildings/{buildingId}';
};

export type GetBuildingErrors = {
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type GetBuildingError = GetBuildingErrors[keyof GetBuildingErrors];

export type GetBuildingResponses = {
    /**
     * Building details
     */
    200: Building;
};

export type GetBuildingResponse = GetBuildingResponses[keyof GetBuildingResponses];

export type UpdateBuildingData = {
    body: UpdateBuildingRequest;
    path: {
        buildingId: string;
    };
    query?: never;
    url: '/buildings/{buildingId}';
};

export type UpdateBuildingErrors = {
    /**
     * Bad request - validation error
     */
    400: ErrorResponse;
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type UpdateBuildingError = UpdateBuildingErrors[keyof UpdateBuildingErrors];

export type UpdateBuildingResponses = {
    /**
     * Building updated
     */
    200: Building;
};

export type UpdateBuildingResponse = UpdateBuildingResponses[keyof UpdateBuildingResponses];

export type GetBuildingBlockingData = {
    body?: never;
    path: {
        buildingId: string;
    };
    query?: {
        /**
         * Expand recurring rules for date range
         */
        includeRecurring?: boolean;
        /**
         * Start date for expanding recurring rules
         */
        startDate?: string;
        /**
         * End date for expanding recurring rules
         */
        endDate?: string;
    };
    url: '/buildings/{buildingId}/blocking';
};

export type GetBuildingBlockingErrors = {
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type GetBuildingBlockingError = GetBuildingBlockingErrors[keyof GetBuildingBlockingErrors];

export type GetBuildingBlockingResponses = {
    /**
     * Building blocking periods
     */
    200: Array<Blocking>;
};

export type GetBuildingBlockingResponse = GetBuildingBlockingResponses[keyof GetBuildingBlockingResponses];

export type ReplaceBuildingBlockingData = {
    body: {
        blockings: Array<CreateBlockingRequest>;
    };
    path: {
        buildingId: string;
    };
    query?: never;
    url: '/buildings/{buildingId}/blocking';
};

export type ReplaceBuildingBlockingErrors = {
    /**
     * Bad request - validation error
     */
    400: ErrorResponse;
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type ReplaceBuildingBlockingError = ReplaceBuildingBlockingErrors[keyof ReplaceBuildingBlockingErrors];

export type ReplaceBuildingBlockingResponses = {
    /**
     * Blocking periods replaced
     */
    200: Array<Blocking>;
};

export type ReplaceBuildingBlockingResponse = ReplaceBuildingBlockingResponses[keyof ReplaceBuildingBlockingResponses];

export type RemoveBuildingBlockingEntriesData = {
    body: {
        blockingIds: Array<string>;
    };
    path: {
        buildingId: string;
    };
    query?: never;
    url: '/buildings/{buildingId}/blocking/entries';
};

export type RemoveBuildingBlockingEntriesErrors = {
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type RemoveBuildingBlockingEntriesError = RemoveBuildingBlockingEntriesErrors[keyof RemoveBuildingBlockingEntriesErrors];

export type RemoveBuildingBlockingEntriesResponses = {
    /**
     * Blocking periods removed
     */
    204: void;
};

export type RemoveBuildingBlockingEntriesResponse = RemoveBuildingBlockingEntriesResponses[keyof RemoveBuildingBlockingEntriesResponses];

export type AddBuildingBlockingEntriesData = {
    body: {
        entries: Array<CreateBlockingRequest>;
    };
    path: {
        buildingId: string;
    };
    query?: never;
    url: '/buildings/{buildingId}/blocking/entries';
};

export type AddBuildingBlockingEntriesErrors = {
    /**
     * Bad request - validation error
     */
    400: ErrorResponse;
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type AddBuildingBlockingEntriesError = AddBuildingBlockingEntriesErrors[keyof AddBuildingBlockingEntriesErrors];

export type AddBuildingBlockingEntriesResponses = {
    /**
     * Blocking periods added
     */
    201: Array<Blocking>;
};

export type AddBuildingBlockingEntriesResponse = AddBuildingBlockingEntriesResponses[keyof AddBuildingBlockingEntriesResponses];

export type ListBuildingAreasData = {
    body?: never;
    path: {
        buildingId: string;
    };
    query?: never;
    url: '/buildings/{buildingId}/areas';
};

export type ListBuildingAreasErrors = {
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type ListBuildingAreasError = ListBuildingAreasErrors[keyof ListBuildingAreasErrors];

export type ListBuildingAreasResponses = {
    /**
     * List of areas
     */
    200: Array<Area>;
};

export type ListBuildingAreasResponse = ListBuildingAreasResponses[keyof ListBuildingAreasResponses];

export type GetBuildingAvailabilityData = {
    body?: never;
    path: {
        buildingId: string;
    };
    query: {
        startDate: string;
        endDate: string;
    };
    url: '/buildings/{buildingId}/availability';
};

export type GetBuildingAvailabilityErrors = {
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type GetBuildingAvailabilityError = GetBuildingAvailabilityErrors[keyof GetBuildingAvailabilityErrors];

export type GetBuildingAvailabilityResponses = {
    /**
     * Available time ranges
     */
    200: Array<TimeRange>;
};

export type GetBuildingAvailabilityResponse = GetBuildingAvailabilityResponses[keyof GetBuildingAvailabilityResponses];

export type GetBuildingCalendarData = {
    body?: never;
    path: {
        buildingId: string;
    };
    query?: never;
    url: '/buildings/{buildingId}/calendar.ics';
};

export type GetBuildingCalendarErrors = {
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type GetBuildingCalendarError = GetBuildingCalendarErrors[keyof GetBuildingCalendarErrors];

export type GetBuildingCalendarResponses = {
    /**
     * iCalendar feed
     */
    200: string;
};

export type GetBuildingCalendarResponse = GetBuildingCalendarResponses[keyof GetBuildingCalendarResponses];

export type ListAreasData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by building
         */
        buildingId?: string;
        /**
         * Page number (1-indexed)
         */
        page?: number;
        /**
         * Items per page
         */
        limit?: number;
    };
    url: '/areas';
};

export type ListAreasResponses = {
    /**
     * List of areas
     */
    200: PaginatedAreaList;
};

export type ListAreasResponse = ListAreasResponses[keyof ListAreasResponses];

export type CreateAreaData = {
    body: CreateAreaRequest;
    path?: never;
    query?: never;
    url: '/areas';
};

export type CreateAreaErrors = {
    /**
     * Bad request - validation error
     */
    400: ErrorResponse;
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
};

export type CreateAreaError = CreateAreaErrors[keyof CreateAreaErrors];

export type CreateAreaResponses = {
    /**
     * Area created
     */
    201: Area;
};

export type CreateAreaResponse = CreateAreaResponses[keyof CreateAreaResponses];

export type DeleteAreaData = {
    body?: never;
    path: {
        areaId: string;
    };
    query?: never;
    url: '/areas/{areaId}';
};

export type DeleteAreaErrors = {
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type DeleteAreaError = DeleteAreaErrors[keyof DeleteAreaErrors];

export type DeleteAreaResponses = {
    /**
     * Area deleted
     */
    204: void;
};

export type DeleteAreaResponse = DeleteAreaResponses[keyof DeleteAreaResponses];

export type GetAreaData = {
    body?: never;
    path: {
        areaId: string;
    };
    query?: never;
    url: '/areas/{areaId}';
};

export type GetAreaErrors = {
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type GetAreaError = GetAreaErrors[keyof GetAreaErrors];

export type GetAreaResponses = {
    /**
     * Area details
     */
    200: Area;
};

export type GetAreaResponse = GetAreaResponses[keyof GetAreaResponses];

export type UpdateAreaData = {
    body: UpdateAreaRequest;
    path: {
        areaId: string;
    };
    query?: never;
    url: '/areas/{areaId}';
};

export type UpdateAreaErrors = {
    /**
     * Bad request - validation error
     */
    400: ErrorResponse;
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type UpdateAreaError = UpdateAreaErrors[keyof UpdateAreaErrors];

export type UpdateAreaResponses = {
    /**
     * Area updated
     */
    200: Area;
};

export type UpdateAreaResponse = UpdateAreaResponses[keyof UpdateAreaResponses];

export type DeleteAreaRoomPlanData = {
    body?: never;
    path: {
        areaId: string;
    };
    query?: never;
    url: '/areas/{areaId}/roomPlan';
};

export type DeleteAreaRoomPlanErrors = {
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type DeleteAreaRoomPlanError = DeleteAreaRoomPlanErrors[keyof DeleteAreaRoomPlanErrors];

export type DeleteAreaRoomPlanResponses = {
    /**
     * Room plan deleted
     */
    204: void;
};

export type DeleteAreaRoomPlanResponse = DeleteAreaRoomPlanResponses[keyof DeleteAreaRoomPlanResponses];

export type GetAreaRoomPlanData = {
    body?: never;
    path: {
        areaId: string;
    };
    query?: never;
    url: '/areas/{areaId}/roomPlan';
};

export type GetAreaRoomPlanErrors = {
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type GetAreaRoomPlanError = GetAreaRoomPlanErrors[keyof GetAreaRoomPlanErrors];

export type GetAreaRoomPlanResponses = {
    /**
     * Room plan data
     */
    200: RoomPlan;
};

export type GetAreaRoomPlanResponse = GetAreaRoomPlanResponses[keyof GetAreaRoomPlanResponses];

export type UpdateAreaRoomPlanData = {
    body: {
        /**
         * Room plan image file
         */
        image?: Blob | File;
        /**
         * JSON array of PlaceMarker objects
         */
        markers?: string;
    };
    path: {
        areaId: string;
    };
    query?: never;
    url: '/areas/{areaId}/roomPlan';
};

export type UpdateAreaRoomPlanErrors = {
    /**
     * Bad request - validation error
     */
    400: ErrorResponse;
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type UpdateAreaRoomPlanError = UpdateAreaRoomPlanErrors[keyof UpdateAreaRoomPlanErrors];

export type UpdateAreaRoomPlanResponses = {
    /**
     * Room plan updated
     */
    200: RoomPlan;
};

export type UpdateAreaRoomPlanResponse = UpdateAreaRoomPlanResponses[keyof UpdateAreaRoomPlanResponses];

export type RemoveAreaRoomPlanMarkersData = {
    body: {
        markerIds: Array<string>;
    };
    path: {
        areaId: string;
    };
    query?: never;
    url: '/areas/{areaId}/roomPlan/markers';
};

export type RemoveAreaRoomPlanMarkersErrors = {
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type RemoveAreaRoomPlanMarkersError = RemoveAreaRoomPlanMarkersErrors[keyof RemoveAreaRoomPlanMarkersErrors];

export type RemoveAreaRoomPlanMarkersResponses = {
    /**
     * Markers removed
     */
    204: void;
};

export type RemoveAreaRoomPlanMarkersResponse = RemoveAreaRoomPlanMarkersResponses[keyof RemoveAreaRoomPlanMarkersResponses];

export type AddAreaRoomPlanMarkersData = {
    body: {
        markers: Array<CreatePlaceMarkerRequest>;
    };
    path: {
        areaId: string;
    };
    query?: never;
    url: '/areas/{areaId}/roomPlan/markers';
};

export type AddAreaRoomPlanMarkersErrors = {
    /**
     * Bad request - validation error
     */
    400: ErrorResponse;
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type AddAreaRoomPlanMarkersError = AddAreaRoomPlanMarkersErrors[keyof AddAreaRoomPlanMarkersErrors];

export type AddAreaRoomPlanMarkersResponses = {
    /**
     * Markers added
     */
    201: Array<PlaceMarker>;
};

export type AddAreaRoomPlanMarkersResponse = AddAreaRoomPlanMarkersResponses[keyof AddAreaRoomPlanMarkersResponses];

export type GetAreaBlockingData = {
    body?: never;
    path: {
        areaId: string;
    };
    query?: {
        /**
         * Include blocking inherited from building
         */
        includeInherited?: boolean;
        /**
         * Expand recurring rules for date range
         */
        includeRecurring?: boolean;
        startDate?: string;
        endDate?: string;
    };
    url: '/areas/{areaId}/blocking';
};

export type GetAreaBlockingErrors = {
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type GetAreaBlockingError = GetAreaBlockingErrors[keyof GetAreaBlockingErrors];

export type GetAreaBlockingResponses = {
    /**
     * Area blocking periods
     */
    200: Array<Blocking>;
};

export type GetAreaBlockingResponse = GetAreaBlockingResponses[keyof GetAreaBlockingResponses];

export type ReplaceAreaBlockingData = {
    body: {
        blockings: Array<CreateBlockingRequest>;
    };
    path: {
        areaId: string;
    };
    query?: never;
    url: '/areas/{areaId}/blocking';
};

export type ReplaceAreaBlockingErrors = {
    /**
     * Bad request - validation error
     */
    400: ErrorResponse;
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type ReplaceAreaBlockingError = ReplaceAreaBlockingErrors[keyof ReplaceAreaBlockingErrors];

export type ReplaceAreaBlockingResponses = {
    /**
     * Blocking periods replaced
     */
    200: Array<Blocking>;
};

export type ReplaceAreaBlockingResponse = ReplaceAreaBlockingResponses[keyof ReplaceAreaBlockingResponses];

export type RemoveAreaBlockingEntriesData = {
    body: {
        blockingIds: Array<string>;
    };
    path: {
        areaId: string;
    };
    query?: never;
    url: '/areas/{areaId}/blocking/entries';
};

export type RemoveAreaBlockingEntriesErrors = {
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type RemoveAreaBlockingEntriesError = RemoveAreaBlockingEntriesErrors[keyof RemoveAreaBlockingEntriesErrors];

export type RemoveAreaBlockingEntriesResponses = {
    /**
     * Blocking periods removed
     */
    204: void;
};

export type RemoveAreaBlockingEntriesResponse = RemoveAreaBlockingEntriesResponses[keyof RemoveAreaBlockingEntriesResponses];

export type AddAreaBlockingEntriesData = {
    body: {
        entries: Array<CreateBlockingRequest>;
    };
    path: {
        areaId: string;
    };
    query?: never;
    url: '/areas/{areaId}/blocking/entries';
};

export type AddAreaBlockingEntriesErrors = {
    /**
     * Bad request - validation error
     */
    400: ErrorResponse;
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type AddAreaBlockingEntriesError = AddAreaBlockingEntriesErrors[keyof AddAreaBlockingEntriesErrors];

export type AddAreaBlockingEntriesResponses = {
    /**
     * Blocking periods added
     */
    201: Array<Blocking>;
};

export type AddAreaBlockingEntriesResponse = AddAreaBlockingEntriesResponses[keyof AddAreaBlockingEntriesResponses];

export type ListAreaPlacesData = {
    body?: never;
    path: {
        areaId: string;
    };
    query?: never;
    url: '/areas/{areaId}/places';
};

export type ListAreaPlacesErrors = {
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type ListAreaPlacesError = ListAreaPlacesErrors[keyof ListAreaPlacesErrors];

export type ListAreaPlacesResponses = {
    /**
     * List of places
     */
    200: Array<Place>;
};

export type ListAreaPlacesResponse = ListAreaPlacesResponses[keyof ListAreaPlacesResponses];

export type GetAreaAvailabilityData = {
    body?: never;
    path: {
        areaId: string;
    };
    query: {
        date: string;
        startTime?: string;
        endTime?: string;
    };
    url: '/areas/{areaId}/availability';
};

export type GetAreaAvailabilityErrors = {
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type GetAreaAvailabilityError = GetAreaAvailabilityErrors[keyof GetAreaAvailabilityErrors];

export type GetAreaAvailabilityResponses = {
    /**
     * Place availability summary
     */
    200: Array<PlaceAvailability>;
};

export type GetAreaAvailabilityResponse = GetAreaAvailabilityResponses[keyof GetAreaAvailabilityResponses];

export type GetAreaCalendarData = {
    body?: never;
    path: {
        areaId: string;
    };
    query?: never;
    url: '/areas/{areaId}/calendar.ics';
};

export type GetAreaCalendarErrors = {
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type GetAreaCalendarError = GetAreaCalendarErrors[keyof GetAreaCalendarErrors];

export type GetAreaCalendarResponses = {
    /**
     * iCalendar feed
     */
    200: string;
};

export type GetAreaCalendarResponse = GetAreaCalendarResponses[keyof GetAreaCalendarResponses];

export type ListPlacesData = {
    body?: never;
    path?: never;
    query?: {
        areaId?: string;
        buildingId?: string;
        search?: string;
        /**
         * Filter by equipment IDs (comma-separated)
         */
        equipment?: Array<string>;
        minCapacity?: number;
        /**
         * Filter by availability
         */
        available?: boolean;
        date?: string;
        startTime?: string;
        endTime?: string;
        /**
         * Page number (1-indexed)
         */
        page?: number;
        /**
         * Items per page
         */
        limit?: number;
    };
    url: '/places';
};

export type ListPlacesResponses = {
    /**
     * List of places
     */
    200: PaginatedPlaceList;
};

export type ListPlacesResponse = ListPlacesResponses[keyof ListPlacesResponses];

export type CreatePlaceData = {
    body: CreatePlaceRequest;
    path?: never;
    query?: never;
    url: '/places';
};

export type CreatePlaceErrors = {
    /**
     * Bad request - validation error
     */
    400: ErrorResponse;
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
};

export type CreatePlaceError = CreatePlaceErrors[keyof CreatePlaceErrors];

export type CreatePlaceResponses = {
    /**
     * Place created
     */
    201: Place;
};

export type CreatePlaceResponse = CreatePlaceResponses[keyof CreatePlaceResponses];

export type DeletePlaceData = {
    body?: never;
    path: {
        placeId: string;
    };
    query?: never;
    url: '/places/{placeId}';
};

export type DeletePlaceErrors = {
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type DeletePlaceError = DeletePlaceErrors[keyof DeletePlaceErrors];

export type DeletePlaceResponses = {
    /**
     * Place deleted
     */
    204: void;
};

export type DeletePlaceResponse = DeletePlaceResponses[keyof DeletePlaceResponses];

export type GetPlaceData = {
    body?: never;
    path: {
        placeId: string;
    };
    query?: never;
    url: '/places/{placeId}';
};

export type GetPlaceErrors = {
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type GetPlaceError = GetPlaceErrors[keyof GetPlaceErrors];

export type GetPlaceResponses = {
    /**
     * Place details
     */
    200: Place;
};

export type GetPlaceResponse = GetPlaceResponses[keyof GetPlaceResponses];

export type UpdatePlaceData = {
    body: UpdatePlaceRequest;
    path: {
        placeId: string;
    };
    query?: never;
    url: '/places/{placeId}';
};

export type UpdatePlaceErrors = {
    /**
     * Bad request - validation error
     */
    400: ErrorResponse;
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type UpdatePlaceError = UpdatePlaceErrors[keyof UpdatePlaceErrors];

export type UpdatePlaceResponses = {
    /**
     * Place updated
     */
    200: Place;
};

export type UpdatePlaceResponse = UpdatePlaceResponses[keyof UpdatePlaceResponses];

export type GetPlaceConstraintsData = {
    body?: never;
    path: {
        placeId: string;
    };
    query?: never;
    url: '/places/{placeId}/constraints';
};

export type GetPlaceConstraintsErrors = {
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type GetPlaceConstraintsError = GetPlaceConstraintsErrors[keyof GetPlaceConstraintsErrors];

export type GetPlaceConstraintsResponses = {
    /**
     * Place constraints
     */
    200: PlaceConstraints;
};

export type GetPlaceConstraintsResponse = GetPlaceConstraintsResponses[keyof GetPlaceConstraintsResponses];

export type UpdatePlaceConstraintsData = {
    body: PlaceConstraints;
    path: {
        placeId: string;
    };
    query?: never;
    url: '/places/{placeId}/constraints';
};

export type UpdatePlaceConstraintsErrors = {
    /**
     * Bad request - validation error
     */
    400: ErrorResponse;
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type UpdatePlaceConstraintsError = UpdatePlaceConstraintsErrors[keyof UpdatePlaceConstraintsErrors];

export type UpdatePlaceConstraintsResponses = {
    /**
     * Constraints updated
     */
    200: PlaceConstraints;
};

export type UpdatePlaceConstraintsResponse = UpdatePlaceConstraintsResponses[keyof UpdatePlaceConstraintsResponses];

export type GetPlaceTimeSlotsData = {
    body?: never;
    path: {
        placeId: string;
    };
    query?: never;
    url: '/places/{placeId}/timeSlots';
};

export type GetPlaceTimeSlotsErrors = {
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type GetPlaceTimeSlotsError = GetPlaceTimeSlotsErrors[keyof GetPlaceTimeSlotsErrors];

export type GetPlaceTimeSlotsResponses = {
    /**
     * Time slot configuration
     */
    200: TimeSlotConfig;
};

export type GetPlaceTimeSlotsResponse = GetPlaceTimeSlotsResponses[keyof GetPlaceTimeSlotsResponses];

export type UpdatePlaceTimeSlotsData = {
    body: TimeSlotConfig;
    path: {
        placeId: string;
    };
    query?: never;
    url: '/places/{placeId}/timeSlots';
};

export type UpdatePlaceTimeSlotsErrors = {
    /**
     * Bad request - validation error
     */
    400: ErrorResponse;
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type UpdatePlaceTimeSlotsError = UpdatePlaceTimeSlotsErrors[keyof UpdatePlaceTimeSlotsErrors];

export type UpdatePlaceTimeSlotsResponses = {
    /**
     * Time slot configuration updated
     */
    200: TimeSlotConfig;
};

export type UpdatePlaceTimeSlotsResponse = UpdatePlaceTimeSlotsResponses[keyof UpdatePlaceTimeSlotsResponses];

export type RemovePlaceEquipmentData = {
    body: {
        equipmentIds: Array<string>;
    };
    path: {
        placeId: string;
    };
    query?: never;
    url: '/places/{placeId}/equipment';
};

export type RemovePlaceEquipmentErrors = {
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type RemovePlaceEquipmentError = RemovePlaceEquipmentErrors[keyof RemovePlaceEquipmentErrors];

export type RemovePlaceEquipmentResponses = {
    /**
     * Equipment removed
     */
    204: void;
};

export type RemovePlaceEquipmentResponse = RemovePlaceEquipmentResponses[keyof RemovePlaceEquipmentResponses];

export type GetPlaceEquipmentData = {
    body?: never;
    path: {
        placeId: string;
    };
    query?: never;
    url: '/places/{placeId}/equipment';
};

export type GetPlaceEquipmentErrors = {
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type GetPlaceEquipmentError = GetPlaceEquipmentErrors[keyof GetPlaceEquipmentErrors];

export type GetPlaceEquipmentResponses = {
    /**
     * Place equipment
     */
    200: Array<Equipment>;
};

export type GetPlaceEquipmentResponse = GetPlaceEquipmentResponses[keyof GetPlaceEquipmentResponses];

export type AddPlaceEquipmentData = {
    body: {
        equipmentIds: Array<string>;
    };
    path: {
        placeId: string;
    };
    query?: never;
    url: '/places/{placeId}/equipment';
};

export type AddPlaceEquipmentErrors = {
    /**
     * Bad request - validation error
     */
    400: ErrorResponse;
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type AddPlaceEquipmentError = AddPlaceEquipmentErrors[keyof AddPlaceEquipmentErrors];

export type AddPlaceEquipmentResponses = {
    /**
     * Equipment added
     */
    200: Array<Equipment>;
};

export type AddPlaceEquipmentResponse = AddPlaceEquipmentResponses[keyof AddPlaceEquipmentResponses];

export type RemovePlaceWhitelistUsersData = {
    body: {
        userIds: Array<string>;
    };
    path: {
        placeId: string;
    };
    query?: never;
    url: '/places/{placeId}/whitelist';
};

export type RemovePlaceWhitelistUsersErrors = {
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type RemovePlaceWhitelistUsersError = RemovePlaceWhitelistUsersErrors[keyof RemovePlaceWhitelistUsersErrors];

export type RemovePlaceWhitelistUsersResponses = {
    /**
     * Users removed from whitelist
     */
    204: void;
};

export type RemovePlaceWhitelistUsersResponse = RemovePlaceWhitelistUsersResponses[keyof RemovePlaceWhitelistUsersResponses];

export type GetPlaceWhitelistData = {
    body?: never;
    path: {
        placeId: string;
    };
    query?: never;
    url: '/places/{placeId}/whitelist';
};

export type GetPlaceWhitelistErrors = {
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type GetPlaceWhitelistError = GetPlaceWhitelistErrors[keyof GetPlaceWhitelistErrors];

export type GetPlaceWhitelistResponses = {
    /**
     * Whitelist users
     */
    200: Array<UserReference>;
};

export type GetPlaceWhitelistResponse = GetPlaceWhitelistResponses[keyof GetPlaceWhitelistResponses];

export type AddPlaceWhitelistUsersData = {
    body: {
        userIds: Array<string>;
    };
    path: {
        placeId: string;
    };
    query?: never;
    url: '/places/{placeId}/whitelist';
};

export type AddPlaceWhitelistUsersErrors = {
    /**
     * Bad request - validation error
     */
    400: ErrorResponse;
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type AddPlaceWhitelistUsersError = AddPlaceWhitelistUsersErrors[keyof AddPlaceWhitelistUsersErrors];

export type AddPlaceWhitelistUsersResponses = {
    /**
     * Users added to whitelist
     */
    200: Array<UserReference>;
};

export type AddPlaceWhitelistUsersResponse = AddPlaceWhitelistUsersResponses[keyof AddPlaceWhitelistUsersResponses];

export type GetPlaceBlockingData = {
    body?: never;
    path: {
        placeId: string;
    };
    query?: {
        /**
         * Include blocking inherited from area and building
         */
        includeInherited?: boolean;
        /**
         * Expand recurring rules for date range
         */
        includeRecurring?: boolean;
        startDate?: string;
        endDate?: string;
    };
    url: '/places/{placeId}/blocking';
};

export type GetPlaceBlockingErrors = {
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type GetPlaceBlockingError = GetPlaceBlockingErrors[keyof GetPlaceBlockingErrors];

export type GetPlaceBlockingResponses = {
    /**
     * Place blocking periods
     */
    200: Array<Blocking>;
};

export type GetPlaceBlockingResponse = GetPlaceBlockingResponses[keyof GetPlaceBlockingResponses];

export type ReplacePlaceBlockingData = {
    body: {
        blockings: Array<CreateBlockingRequest>;
    };
    path: {
        placeId: string;
    };
    query?: never;
    url: '/places/{placeId}/blocking';
};

export type ReplacePlaceBlockingErrors = {
    /**
     * Bad request - validation error
     */
    400: ErrorResponse;
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type ReplacePlaceBlockingError = ReplacePlaceBlockingErrors[keyof ReplacePlaceBlockingErrors];

export type ReplacePlaceBlockingResponses = {
    /**
     * Blocking periods replaced
     */
    200: Array<Blocking>;
};

export type ReplacePlaceBlockingResponse = ReplacePlaceBlockingResponses[keyof ReplacePlaceBlockingResponses];

export type RemovePlaceBlockingEntriesData = {
    body: {
        blockingIds: Array<string>;
    };
    path: {
        placeId: string;
    };
    query?: never;
    url: '/places/{placeId}/blocking/entries';
};

export type RemovePlaceBlockingEntriesErrors = {
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type RemovePlaceBlockingEntriesError = RemovePlaceBlockingEntriesErrors[keyof RemovePlaceBlockingEntriesErrors];

export type RemovePlaceBlockingEntriesResponses = {
    /**
     * Blocking periods removed
     */
    204: void;
};

export type RemovePlaceBlockingEntriesResponse = RemovePlaceBlockingEntriesResponses[keyof RemovePlaceBlockingEntriesResponses];

export type AddPlaceBlockingEntriesData = {
    body: {
        entries: Array<CreateBlockingRequest>;
    };
    path: {
        placeId: string;
    };
    query?: never;
    url: '/places/{placeId}/blocking/entries';
};

export type AddPlaceBlockingEntriesErrors = {
    /**
     * Bad request - validation error
     */
    400: ErrorResponse;
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type AddPlaceBlockingEntriesError = AddPlaceBlockingEntriesErrors[keyof AddPlaceBlockingEntriesErrors];

export type AddPlaceBlockingEntriesResponses = {
    /**
     * Blocking periods added
     */
    201: Array<Blocking>;
};

export type AddPlaceBlockingEntriesResponse = AddPlaceBlockingEntriesResponses[keyof AddPlaceBlockingEntriesResponses];

export type GetPlaceAvailabilityData = {
    body?: never;
    path: {
        placeId: string;
    };
    query: {
        startDate: string;
        endDate: string;
    };
    url: '/places/{placeId}/availability';
};

export type GetPlaceAvailabilityErrors = {
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type GetPlaceAvailabilityError = GetPlaceAvailabilityErrors[keyof GetPlaceAvailabilityErrors];

export type GetPlaceAvailabilityResponses = {
    /**
     * Availability slots
     */
    200: Array<AvailabilitySlot>;
};

export type GetPlaceAvailabilityResponse = GetPlaceAvailabilityResponses[keyof GetPlaceAvailabilityResponses];

export type GetPlaceQrCodeData = {
    body?: never;
    path: {
        placeId: string;
    };
    query?: {
        templateId?: string;
        format?: 'png' | 'jpg' | 'pdf';
        /**
         * Details to include (comma-separated)
         */
        includeDetails?: Array<'name' | 'areaName' | 'buildingName'>;
    };
    url: '/places/{placeId}/qrCode';
};

export type GetPlaceQrCodeErrors = {
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type GetPlaceQrCodeError = GetPlaceQrCodeErrors[keyof GetPlaceQrCodeErrors];

export type GetPlaceQrCodeResponses = {
    /**
     * QR code image
     */
    200: Blob | File;
};

export type GetPlaceQrCodeResponse = GetPlaceQrCodeResponses[keyof GetPlaceQrCodeResponses];

export type GetPlaceCalendarData = {
    body?: never;
    path: {
        placeId: string;
    };
    query?: never;
    url: '/places/{placeId}/calendar.ics';
};

export type GetPlaceCalendarErrors = {
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type GetPlaceCalendarError = GetPlaceCalendarErrors[keyof GetPlaceCalendarErrors];

export type GetPlaceCalendarResponses = {
    /**
     * iCalendar feed
     */
    200: string;
};

export type GetPlaceCalendarResponse = GetPlaceCalendarResponses[keyof GetPlaceCalendarResponses];

export type ListReservationsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by user (admin only)
         */
        userId?: string;
        placeId?: string;
        areaId?: string;
        buildingId?: string;
        status?: 'upcoming' | 'active' | 'past' | 'cancelled';
        startDate?: string;
        endDate?: string;
        /**
         * Page number (1-indexed)
         */
        page?: number;
        /**
         * Items per page
         */
        limit?: number;
    };
    url: '/reservations';
};

export type ListReservationsErrors = {
    /**
     * Unauthorized - not authenticated
     */
    401: ErrorResponse;
};

export type ListReservationsError = ListReservationsErrors[keyof ListReservationsErrors];

export type ListReservationsResponses = {
    /**
     * List of reservations
     */
    200: PaginatedReservationList;
};

export type ListReservationsResponse = ListReservationsResponses[keyof ListReservationsResponses];

export type CreateReservationData = {
    body: CreateReservationRequest;
    path?: never;
    query?: never;
    url: '/reservations';
};

export type CreateReservationErrors = {
    /**
     * Bad request - validation error
     */
    400: ErrorResponse;
    /**
     * Unauthorized - not authenticated
     */
    401: ErrorResponse;
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Conflict - overlapping reservation or blocked time slot
     */
    409: ErrorResponse;
};

export type CreateReservationError = CreateReservationErrors[keyof CreateReservationErrors];

export type CreateReservationResponses = {
    /**
     * Reservation(s) created
     */
    201: Reservation | Array<Reservation>;
};

export type CreateReservationResponse = CreateReservationResponses[keyof CreateReservationResponses];

export type CancelReservationData = {
    body?: never;
    path: {
        reservationId: string;
    };
    query?: never;
    url: '/reservations/{reservationId}';
};

export type CancelReservationErrors = {
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type CancelReservationError = CancelReservationErrors[keyof CancelReservationErrors];

export type CancelReservationResponses = {
    /**
     * Reservation cancelled
     */
    204: void;
};

export type CancelReservationResponse = CancelReservationResponses[keyof CancelReservationResponses];

export type GetReservationData = {
    body?: never;
    path: {
        reservationId: string;
    };
    query?: never;
    url: '/reservations/{reservationId}';
};

export type GetReservationErrors = {
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type GetReservationError = GetReservationErrors[keyof GetReservationErrors];

export type GetReservationResponses = {
    /**
     * Reservation details
     */
    200: Reservation;
};

export type GetReservationResponse = GetReservationResponses[keyof GetReservationResponses];

export type UpdateReservationData = {
    body: UpdateReservationRequest;
    path: {
        reservationId: string;
    };
    query?: never;
    url: '/reservations/{reservationId}';
};

export type UpdateReservationErrors = {
    /**
     * Bad request - validation error
     */
    400: ErrorResponse;
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Resource not found
     */
    404: ErrorResponse;
    /**
     * Conflict - overlapping reservation or blocked time slot
     */
    409: ErrorResponse;
};

export type UpdateReservationError = UpdateReservationErrors[keyof UpdateReservationErrors];

export type UpdateReservationResponses = {
    /**
     * Reservation updated
     */
    200: Reservation;
};

export type UpdateReservationResponse = UpdateReservationResponses[keyof UpdateReservationResponses];

export type CheckInReservationData = {
    body?: {
        /**
         * Optional QR code for verification
         */
        qrCode?: string;
    };
    path: {
        reservationId: string;
    };
    query?: never;
    url: '/reservations/{reservationId}/checkIn';
};

export type CheckInReservationErrors = {
    /**
     * Bad request - validation error
     */
    400: ErrorResponse;
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type CheckInReservationError = CheckInReservationErrors[keyof CheckInReservationErrors];

export type CheckInReservationResponses = {
    /**
     * Check-in successful
     */
    200: Reservation;
};

export type CheckInReservationResponse = CheckInReservationResponses[keyof CheckInReservationResponses];

export type GetReservationShareLinkData = {
    body?: never;
    path: {
        reservationId: string;
    };
    query?: never;
    url: '/reservations/{reservationId}/share';
};

export type GetReservationShareLinkErrors = {
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type GetReservationShareLinkError = GetReservationShareLinkErrors[keyof GetReservationShareLinkErrors];

export type GetReservationShareLinkResponses = {
    /**
     * Share link and metadata
     */
    200: ShareResponse;
};

export type GetReservationShareLinkResponse = GetReservationShareLinkResponses[keyof GetReservationShareLinkResponses];

export type ExportReservationsData = {
    body?: never;
    path?: never;
    query: {
        startDate: string;
        endDate: string;
        buildingId?: string;
        areaId?: string;
    };
    url: '/reservations/export';
};

export type ExportReservationsErrors = {
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
};

export type ExportReservationsError = ExportReservationsErrors[keyof ExportReservationsErrors];

export type ExportReservationsResponses = {
    /**
     * CSV export
     */
    200: string;
};

export type ExportReservationsResponse = ExportReservationsResponses[keyof ExportReservationsResponses];

export type ListUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Search by email or name
         */
        search?: string;
        /**
         * Filter by group IDs (comma-separated)
         */
        groupIds?: Array<string>;
        status?: 'active' | 'disabled';
        /**
         * Page number (1-indexed)
         */
        page?: number;
        /**
         * Items per page
         */
        limit?: number;
    };
    url: '/users';
};

export type ListUsersErrors = {
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
};

export type ListUsersError = ListUsersErrors[keyof ListUsersErrors];

export type ListUsersResponses = {
    /**
     * List of users
     */
    200: PaginatedUserList;
};

export type ListUsersResponse = ListUsersResponses[keyof ListUsersResponses];

export type GetUserData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: never;
    url: '/users/{userId}';
};

export type GetUserErrors = {
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type GetUserError = GetUserErrors[keyof GetUserErrors];

export type GetUserResponses = {
    /**
     * User details
     */
    200: User;
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];

export type UpdateUserData = {
    body: UpdateUserRequest;
    path: {
        userId: string;
    };
    query?: never;
    url: '/users/{userId}';
};

export type UpdateUserErrors = {
    /**
     * Bad request - validation error
     */
    400: ErrorResponse;
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type UpdateUserError = UpdateUserErrors[keyof UpdateUserErrors];

export type UpdateUserResponses = {
    /**
     * User updated
     */
    200: User;
};

export type UpdateUserResponse = UpdateUserResponses[keyof UpdateUserResponses];

export type RemoveUserGroupsData = {
    body: {
        groupIds: Array<string>;
    };
    path: {
        userId: string;
    };
    query?: never;
    url: '/users/{userId}/groups';
};

export type RemoveUserGroupsErrors = {
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type RemoveUserGroupsError = RemoveUserGroupsErrors[keyof RemoveUserGroupsErrors];

export type RemoveUserGroupsResponses = {
    /**
     * Groups removed
     */
    204: void;
};

export type RemoveUserGroupsResponse = RemoveUserGroupsResponses[keyof RemoveUserGroupsResponses];

export type GetUserGroupsData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: never;
    url: '/users/{userId}/groups';
};

export type GetUserGroupsErrors = {
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type GetUserGroupsError = GetUserGroupsErrors[keyof GetUserGroupsErrors];

export type GetUserGroupsResponses = {
    /**
     * User's groups
     */
    200: Array<Group>;
};

export type GetUserGroupsResponse = GetUserGroupsResponses[keyof GetUserGroupsResponses];

export type AddUserGroupsData = {
    body: {
        groupIds: Array<string>;
    };
    path: {
        userId: string;
    };
    query?: never;
    url: '/users/{userId}/groups';
};

export type AddUserGroupsErrors = {
    /**
     * Bad request - validation error
     */
    400: ErrorResponse;
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type AddUserGroupsError = AddUserGroupsErrors[keyof AddUserGroupsErrors];

export type AddUserGroupsResponses = {
    /**
     * Groups added
     */
    200: Array<Group>;
};

export type AddUserGroupsResponse = AddUserGroupsResponses[keyof AddUserGroupsResponses];

export type DisableUserData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: never;
    url: '/users/{userId}/disable';
};

export type DisableUserErrors = {
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type DisableUserError = DisableUserErrors[keyof DisableUserErrors];

export type DisableUserResponses = {
    /**
     * User disabled
     */
    200: User;
};

export type DisableUserResponse = DisableUserResponses[keyof DisableUserResponses];

export type EnableUserData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: never;
    url: '/users/{userId}/enable';
};

export type EnableUserErrors = {
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type EnableUserError = EnableUserErrors[keyof EnableUserErrors];

export type EnableUserResponses = {
    /**
     * User enabled
     */
    200: User;
};

export type EnableUserResponse = EnableUserResponses[keyof EnableUserResponses];

export type RemoveCurrentUserFavoritesData = {
    body: {
        placeIds: Array<string>;
    };
    path?: never;
    query?: never;
    url: '/users/me/favorites';
};

export type RemoveCurrentUserFavoritesErrors = {
    /**
     * Unauthorized - not authenticated
     */
    401: ErrorResponse;
};

export type RemoveCurrentUserFavoritesError = RemoveCurrentUserFavoritesErrors[keyof RemoveCurrentUserFavoritesErrors];

export type RemoveCurrentUserFavoritesResponses = {
    /**
     * Places removed from favorites
     */
    204: void;
};

export type RemoveCurrentUserFavoritesResponse = RemoveCurrentUserFavoritesResponses[keyof RemoveCurrentUserFavoritesResponses];

export type GetCurrentUserFavoritesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me/favorites';
};

export type GetCurrentUserFavoritesErrors = {
    /**
     * Unauthorized - not authenticated
     */
    401: ErrorResponse;
};

export type GetCurrentUserFavoritesError = GetCurrentUserFavoritesErrors[keyof GetCurrentUserFavoritesErrors];

export type GetCurrentUserFavoritesResponses = {
    /**
     * Favorite places
     */
    200: Array<Place>;
};

export type GetCurrentUserFavoritesResponse = GetCurrentUserFavoritesResponses[keyof GetCurrentUserFavoritesResponses];

export type AddCurrentUserFavoritesData = {
    body: {
        placeIds: Array<string>;
    };
    path?: never;
    query?: never;
    url: '/users/me/favorites';
};

export type AddCurrentUserFavoritesErrors = {
    /**
     * Bad request - validation error
     */
    400: ErrorResponse;
    /**
     * Unauthorized - not authenticated
     */
    401: ErrorResponse;
};

export type AddCurrentUserFavoritesError = AddCurrentUserFavoritesErrors[keyof AddCurrentUserFavoritesErrors];

export type AddCurrentUserFavoritesResponses = {
    /**
     * Places added to favorites
     */
    201: unknown;
};

export type GetCurrentUserNotificationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me/notifications';
};

export type GetCurrentUserNotificationsErrors = {
    /**
     * Unauthorized - not authenticated
     */
    401: ErrorResponse;
};

export type GetCurrentUserNotificationsError = GetCurrentUserNotificationsErrors[keyof GetCurrentUserNotificationsErrors];

export type GetCurrentUserNotificationsResponses = {
    /**
     * Notification preferences
     */
    200: NotificationPreferences;
};

export type GetCurrentUserNotificationsResponse = GetCurrentUserNotificationsResponses[keyof GetCurrentUserNotificationsResponses];

export type UpdateCurrentUserNotificationsData = {
    body: NotificationPreferences;
    path?: never;
    query?: never;
    url: '/users/me/notifications';
};

export type UpdateCurrentUserNotificationsErrors = {
    /**
     * Bad request - validation error
     */
    400: ErrorResponse;
    /**
     * Unauthorized - not authenticated
     */
    401: ErrorResponse;
};

export type UpdateCurrentUserNotificationsError = UpdateCurrentUserNotificationsErrors[keyof UpdateCurrentUserNotificationsErrors];

export type UpdateCurrentUserNotificationsResponses = {
    /**
     * Preferences updated
     */
    200: NotificationPreferences;
};

export type UpdateCurrentUserNotificationsResponse = UpdateCurrentUserNotificationsResponses[keyof UpdateCurrentUserNotificationsResponses];

export type ListGroupsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/groups';
};

export type ListGroupsErrors = {
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
};

export type ListGroupsError = ListGroupsErrors[keyof ListGroupsErrors];

export type ListGroupsResponses = {
    /**
     * List of groups
     */
    200: Array<Group>;
};

export type ListGroupsResponse = ListGroupsResponses[keyof ListGroupsResponses];

export type CreateGroupData = {
    body: CreateGroupRequest;
    path?: never;
    query?: never;
    url: '/groups';
};

export type CreateGroupErrors = {
    /**
     * Bad request - validation error
     */
    400: ErrorResponse;
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
};

export type CreateGroupError = CreateGroupErrors[keyof CreateGroupErrors];

export type CreateGroupResponses = {
    /**
     * Group created
     */
    201: Group;
};

export type CreateGroupResponse = CreateGroupResponses[keyof CreateGroupResponses];

export type DeleteGroupData = {
    body?: never;
    path: {
        groupId: string;
    };
    query?: never;
    url: '/groups/{groupId}';
};

export type DeleteGroupErrors = {
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type DeleteGroupError = DeleteGroupErrors[keyof DeleteGroupErrors];

export type DeleteGroupResponses = {
    /**
     * Group deleted
     */
    204: void;
};

export type DeleteGroupResponse = DeleteGroupResponses[keyof DeleteGroupResponses];

export type GetGroupData = {
    body?: never;
    path: {
        groupId: string;
    };
    query?: never;
    url: '/groups/{groupId}';
};

export type GetGroupErrors = {
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type GetGroupError = GetGroupErrors[keyof GetGroupErrors];

export type GetGroupResponses = {
    /**
     * Group details
     */
    200: GroupWithMembers;
};

export type GetGroupResponse = GetGroupResponses[keyof GetGroupResponses];

export type UpdateGroupData = {
    body: UpdateGroupRequest;
    path: {
        groupId: string;
    };
    query?: never;
    url: '/groups/{groupId}';
};

export type UpdateGroupErrors = {
    /**
     * Bad request - validation error
     */
    400: ErrorResponse;
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type UpdateGroupError = UpdateGroupErrors[keyof UpdateGroupErrors];

export type UpdateGroupResponses = {
    /**
     * Group updated
     */
    200: Group;
};

export type UpdateGroupResponse = UpdateGroupResponses[keyof UpdateGroupResponses];

export type RemoveGroupPermissionsData = {
    body: {
        permissions: Array<string>;
    };
    path: {
        groupId: string;
    };
    query?: never;
    url: '/groups/{groupId}/permissions';
};

export type RemoveGroupPermissionsErrors = {
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type RemoveGroupPermissionsError = RemoveGroupPermissionsErrors[keyof RemoveGroupPermissionsErrors];

export type RemoveGroupPermissionsResponses = {
    /**
     * Permissions removed
     */
    204: void;
};

export type RemoveGroupPermissionsResponse = RemoveGroupPermissionsResponses[keyof RemoveGroupPermissionsResponses];

export type GetGroupPermissionsData = {
    body?: never;
    path: {
        groupId: string;
    };
    query?: never;
    url: '/groups/{groupId}/permissions';
};

export type GetGroupPermissionsErrors = {
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type GetGroupPermissionsError = GetGroupPermissionsErrors[keyof GetGroupPermissionsErrors];

export type GetGroupPermissionsResponses = {
    /**
     * Group permissions
     */
    200: Array<Permission>;
};

export type GetGroupPermissionsResponse = GetGroupPermissionsResponses[keyof GetGroupPermissionsResponses];

export type AddGroupPermissionsData = {
    body: {
        permissions: Array<string>;
    };
    path: {
        groupId: string;
    };
    query?: never;
    url: '/groups/{groupId}/permissions';
};

export type AddGroupPermissionsErrors = {
    /**
     * Bad request - validation error
     */
    400: ErrorResponse;
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type AddGroupPermissionsError = AddGroupPermissionsErrors[keyof AddGroupPermissionsErrors];

export type AddGroupPermissionsResponses = {
    /**
     * Permissions added
     */
    200: Array<Permission>;
};

export type AddGroupPermissionsResponse = AddGroupPermissionsResponses[keyof AddGroupPermissionsResponses];

export type GetGroupMembersData = {
    body?: never;
    path: {
        groupId: string;
    };
    query?: never;
    url: '/groups/{groupId}/members';
};

export type GetGroupMembersErrors = {
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type GetGroupMembersError = GetGroupMembersErrors[keyof GetGroupMembersErrors];

export type GetGroupMembersResponses = {
    /**
     * Group members
     */
    200: Array<User>;
};

export type GetGroupMembersResponse = GetGroupMembersResponses[keyof GetGroupMembersResponses];

export type GetDefaultGroupAssignmentData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/groups/defaultAssignment';
};

export type GetDefaultGroupAssignmentErrors = {
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
};

export type GetDefaultGroupAssignmentError = GetDefaultGroupAssignmentErrors[keyof GetDefaultGroupAssignmentErrors];

export type GetDefaultGroupAssignmentResponses = {
    /**
     * Default groups
     */
    200: Array<Group>;
};

export type GetDefaultGroupAssignmentResponse = GetDefaultGroupAssignmentResponses[keyof GetDefaultGroupAssignmentResponses];

export type SetDefaultGroupAssignmentData = {
    body: {
        groupIds: Array<string>;
    };
    path?: never;
    query?: never;
    url: '/groups/defaultAssignment';
};

export type SetDefaultGroupAssignmentErrors = {
    /**
     * Bad request - validation error
     */
    400: ErrorResponse;
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
};

export type SetDefaultGroupAssignmentError = SetDefaultGroupAssignmentErrors[keyof SetDefaultGroupAssignmentErrors];

export type SetDefaultGroupAssignmentResponses = {
    /**
     * Default groups updated
     */
    200: Array<Group>;
};

export type SetDefaultGroupAssignmentResponse = SetDefaultGroupAssignmentResponses[keyof SetDefaultGroupAssignmentResponses];

export type ListPermissionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/permissions';
};

export type ListPermissionsErrors = {
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
};

export type ListPermissionsError = ListPermissionsErrors[keyof ListPermissionsErrors];

export type ListPermissionsResponses = {
    /**
     * Available permissions
     */
    200: Array<Permission>;
};

export type ListPermissionsResponse = ListPermissionsResponses[keyof ListPermissionsResponses];

export type ListEquipmentData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/equipment';
};

export type ListEquipmentResponses = {
    /**
     * List of equipment types
     */
    200: Array<Equipment>;
};

export type ListEquipmentResponse = ListEquipmentResponses[keyof ListEquipmentResponses];

export type CreateEquipmentData = {
    body: CreateEquipmentRequest;
    path?: never;
    query?: never;
    url: '/equipment';
};

export type CreateEquipmentErrors = {
    /**
     * Bad request - validation error
     */
    400: ErrorResponse;
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
};

export type CreateEquipmentError = CreateEquipmentErrors[keyof CreateEquipmentErrors];

export type CreateEquipmentResponses = {
    /**
     * Equipment created
     */
    201: Equipment;
};

export type CreateEquipmentResponse = CreateEquipmentResponses[keyof CreateEquipmentResponses];

export type DeleteEquipmentData = {
    body?: never;
    path: {
        equipmentId: string;
    };
    query?: never;
    url: '/equipment/{equipmentId}';
};

export type DeleteEquipmentErrors = {
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type DeleteEquipmentError = DeleteEquipmentErrors[keyof DeleteEquipmentErrors];

export type DeleteEquipmentResponses = {
    /**
     * Equipment deleted
     */
    204: void;
};

export type DeleteEquipmentResponse = DeleteEquipmentResponses[keyof DeleteEquipmentResponses];

export type GetEquipmentData = {
    body?: never;
    path: {
        equipmentId: string;
    };
    query?: never;
    url: '/equipment/{equipmentId}';
};

export type GetEquipmentErrors = {
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type GetEquipmentError = GetEquipmentErrors[keyof GetEquipmentErrors];

export type GetEquipmentResponses = {
    /**
     * Equipment details
     */
    200: Equipment;
};

export type GetEquipmentResponse = GetEquipmentResponses[keyof GetEquipmentResponses];

export type UpdateEquipmentData = {
    body: UpdateEquipmentRequest;
    path: {
        equipmentId: string;
    };
    query?: never;
    url: '/equipment/{equipmentId}';
};

export type UpdateEquipmentErrors = {
    /**
     * Bad request - validation error
     */
    400: ErrorResponse;
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type UpdateEquipmentError = UpdateEquipmentErrors[keyof UpdateEquipmentErrors];

export type UpdateEquipmentResponses = {
    /**
     * Equipment updated
     */
    200: Equipment;
};

export type UpdateEquipmentResponse = UpdateEquipmentResponses[keyof UpdateEquipmentResponses];

export type GetStatisticsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/statistics';
};

export type GetStatisticsErrors = {
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
};

export type GetStatisticsError = GetStatisticsErrors[keyof GetStatisticsErrors];

export type GetStatisticsResponses = {
    /**
     * Overall statistics
     */
    200: Statistics;
};

export type GetStatisticsResponse = GetStatisticsResponses[keyof GetStatisticsResponses];

export type GetUsageStatisticsData = {
    body?: never;
    path?: never;
    query: {
        period: 'daily' | 'weekly' | 'monthly' | 'yearly';
        startDate: string;
        endDate: string;
        buildingId?: string;
        areaId?: string;
        placeId?: string;
    };
    url: '/statistics/usage';
};

export type GetUsageStatisticsErrors = {
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
};

export type GetUsageStatisticsError = GetUsageStatisticsErrors[keyof GetUsageStatisticsErrors];

export type GetUsageStatisticsResponses = {
    /**
     * Usage statistics
     */
    200: Array<UsageStatistics>;
};

export type GetUsageStatisticsResponse = GetUsageStatisticsResponses[keyof GetUsageStatisticsResponses];

export type GetCurrentOccupancyData = {
    body?: never;
    path?: never;
    query?: {
        buildingId?: string;
        areaId?: string;
    };
    url: '/statistics/current';
};

export type GetCurrentOccupancyErrors = {
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
};

export type GetCurrentOccupancyError = GetCurrentOccupancyErrors[keyof GetCurrentOccupancyErrors];

export type GetCurrentOccupancyResponses = {
    /**
     * Current occupancy
     */
    200: CurrentOccupancy;
};

export type GetCurrentOccupancyResponse = GetCurrentOccupancyResponses[keyof GetCurrentOccupancyResponses];

export type ListQrTemplatesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/qrTemplates';
};

export type ListQrTemplatesErrors = {
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
};

export type ListQrTemplatesError = ListQrTemplatesErrors[keyof ListQrTemplatesErrors];

export type ListQrTemplatesResponses = {
    /**
     * List of templates
     */
    200: Array<QrTemplate>;
};

export type ListQrTemplatesResponse = ListQrTemplatesResponses[keyof ListQrTemplatesResponses];

export type CreateQrTemplateData = {
    body: CreateQrTemplateRequest;
    path?: never;
    query?: never;
    url: '/qrTemplates';
};

export type CreateQrTemplateErrors = {
    /**
     * Bad request - validation error
     */
    400: ErrorResponse;
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
};

export type CreateQrTemplateError = CreateQrTemplateErrors[keyof CreateQrTemplateErrors];

export type CreateQrTemplateResponses = {
    /**
     * Template created
     */
    201: QrTemplate;
};

export type CreateQrTemplateResponse = CreateQrTemplateResponses[keyof CreateQrTemplateResponses];

export type DeleteQrTemplateData = {
    body?: never;
    path: {
        templateId: string;
    };
    query?: never;
    url: '/qrTemplates/{templateId}';
};

export type DeleteQrTemplateErrors = {
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type DeleteQrTemplateError = DeleteQrTemplateErrors[keyof DeleteQrTemplateErrors];

export type DeleteQrTemplateResponses = {
    /**
     * Template deleted
     */
    204: void;
};

export type DeleteQrTemplateResponse = DeleteQrTemplateResponses[keyof DeleteQrTemplateResponses];

export type GetQrTemplateData = {
    body?: never;
    path: {
        templateId: string;
    };
    query?: never;
    url: '/qrTemplates/{templateId}';
};

export type GetQrTemplateErrors = {
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type GetQrTemplateError = GetQrTemplateErrors[keyof GetQrTemplateErrors];

export type GetQrTemplateResponses = {
    /**
     * Template details
     */
    200: QrTemplate;
};

export type GetQrTemplateResponse = GetQrTemplateResponses[keyof GetQrTemplateResponses];

export type UpdateQrTemplateData = {
    body: UpdateQrTemplateRequest;
    path: {
        templateId: string;
    };
    query?: never;
    url: '/qrTemplates/{templateId}';
};

export type UpdateQrTemplateErrors = {
    /**
     * Bad request - validation error
     */
    400: ErrorResponse;
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type UpdateQrTemplateError = UpdateQrTemplateErrors[keyof UpdateQrTemplateErrors];

export type UpdateQrTemplateResponses = {
    /**
     * Template updated
     */
    200: QrTemplate;
};

export type UpdateQrTemplateResponse = UpdateQrTemplateResponses[keyof UpdateQrTemplateResponses];

export type PreviewQrTemplateData = {
    body?: never;
    path: {
        templateId: string;
    };
    query?: never;
    url: '/qrTemplates/{templateId}/preview';
};

export type PreviewQrTemplateErrors = {
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type PreviewQrTemplateError = PreviewQrTemplateErrors[keyof PreviewQrTemplateErrors];

export type PreviewQrTemplateResponses = {
    /**
     * Rendered template preview
     */
    200: string;
};

export type PreviewQrTemplateResponse = PreviewQrTemplateResponses[keyof PreviewQrTemplateResponses];

export type ListApiKeysData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/apiKeys';
};

export type ListApiKeysErrors = {
    /**
     * Unauthorized - not authenticated
     */
    401: ErrorResponse;
};

export type ListApiKeysError = ListApiKeysErrors[keyof ListApiKeysErrors];

export type ListApiKeysResponses = {
    /**
     * List of API keys (masked)
     */
    200: Array<ApiKey>;
};

export type ListApiKeysResponse = ListApiKeysResponses[keyof ListApiKeysResponses];

export type CreateApiKeyData = {
    body: CreateApiKeyRequest;
    path?: never;
    query?: never;
    url: '/apiKeys';
};

export type CreateApiKeyErrors = {
    /**
     * Bad request - validation error
     */
    400: ErrorResponse;
    /**
     * Unauthorized - not authenticated
     */
    401: ErrorResponse;
};

export type CreateApiKeyError = CreateApiKeyErrors[keyof CreateApiKeyErrors];

export type CreateApiKeyResponses = {
    /**
     * API key created (full key shown only once)
     */
    201: ApiKeyWithSecret;
};

export type CreateApiKeyResponse = CreateApiKeyResponses[keyof CreateApiKeyResponses];

export type RevokeApiKeyData = {
    body?: never;
    path: {
        keyId: string;
    };
    query?: never;
    url: '/apiKeys/{keyId}';
};

export type RevokeApiKeyErrors = {
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type RevokeApiKeyError = RevokeApiKeyErrors[keyof RevokeApiKeyErrors];

export type RevokeApiKeyResponses = {
    /**
     * API key revoked
     */
    204: void;
};

export type RevokeApiKeyResponse = RevokeApiKeyResponses[keyof RevokeApiKeyResponses];

export type GetAuditLogData = {
    body?: never;
    path?: never;
    query?: {
        entityType?: 'building' | 'area' | 'place' | 'reservation' | 'user' | 'group';
        entityId?: string;
        /**
         * Filter by who made the change
         */
        userId?: string;
        action?: 'create' | 'update' | 'delete';
        startDate?: string;
        endDate?: string;
        /**
         * Page number (1-indexed)
         */
        page?: number;
        /**
         * Items per page
         */
        limit?: number;
    };
    url: '/auditLog';
};

export type GetAuditLogErrors = {
    /**
     * Forbidden - insufficient permissions
     */
    403: ErrorResponse;
};

export type GetAuditLogError = GetAuditLogErrors[keyof GetAuditLogErrors];

export type GetAuditLogResponses = {
    /**
     * Audit log entries
     */
    200: PaginatedAuditLogList;
};

export type GetAuditLogResponse = GetAuditLogResponses[keyof GetAuditLogResponses];
