package query

//go:generate gorm gen -i .

import (
	"gorm.io/cli/gorm/genconfig"
)

// Config for GORM CLI to generate implementations for the query interfaces.
// This file is generated by running `go run gorm.io/cli/gorm gen -i ./pkg/database/internal/query` in the backend directory.
var _ = genconfig.Config{
	OutPath: "../gen",

	// Include all the query interfaces defined in this package
	IncludeInterfaces: []any{
		ExampleQuery(nil),
	},
}
